version: "3.9"
services:
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: "postgres:12.9"
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dnb
