version: "3.9"
services:
  dnb-main-pg-migrations:
    image: "dnb-main-pg-migrations"
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - postgres

  dnb-main-pg-fixtures:
    image: "dnb-main-pg-fixtures"
    build:
      context: .
      dockerfile: Dockerfile.fixtures
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres:12.9"
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dnb
